#!/usr/bin/env python

import os, sys
BUILD_PATHS = [os.path.join(os.getcwd(), 'build/lib.linux-x86_64-2.4/'),
               os.path.join(os.getcwd(), 'build/lib.darwin-8.5.0-Power_Macintosh-2.3/'),
               ]
sys.path = BUILD_PATHS + sys.path
import rtmidi
import threading


class Collector(threading.Thread):
    def __init__(self, device, port):
        threading.Thread.__init__(self)
        self.setDaemon(True)
        self.port = port
        self.device = device
        self.quit = False

    def run(self):
        device.openPort(self.port, False)
        while True:
            if self.quit:
                return
            msg = self.device.getMessage()
            if msg:
                print 'PORT: %s, MESSAGE: %s' % (self.port, msg)

dev = rtmidi.RtMidiIn()
collectors = []
for i in range(dev.getPortCount()):
    device = rtmidi.RtMidiIn()
    print 'OPENING',dev.getPortName(i)
    collector = Collector(device, i)
    collector.start()
    collectors.append(collector)

print 'HIT ENTER TO EXIT'
sys.stdin.read(1)
for i in collectors:
    collector.quit = True
